services:
  backend:
    build: ./backend
    container_name: backend_app
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - marketpulse_network

  frontend:
    build: ./frontend
    container_name: nextjs_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - marketpulse_network
    environment:
      NEXT_PUBLIC_MARKETPULSE_API_BASE_URL: http://backend:8000

networks:
  marketpulse_network:
    driver: bridge
